name: shared_preferences_settings
description: Settings Screen with Shared Preferences
repository: https://github.com/eocorekuneho/shared_preferences_settings
documentation: https://github.com/eocorekuneho/shared_preferences_settings
homepage: https://github.com/eocorekuneho/shared_preferences_settings

version: 3.0.0

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.0
  rxdart: ^0.27.7
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
